# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/codes/vivado/demo/demo.cache/wt [current_project]
set_property parent.project_path F:/codes/vivado/demo/demo.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  F:/codes/modelsim/MIPS/pipeline_mips处理器实现/regfile.v
  F:/codes/modelsim/MIPS/pipeline_mips处理器实现/DataMem.v
  F:/codes/modelsim/MIPS/pipeline_mips处理器实现/rom.v
  F:/codes/modelsim/MIPS/pipeline_mips处理器实现/Peripheral.v
  F:/codes/modelsim/MIPS/pipeline_mips处理器实现/ALU.v
  F:/codes/modelsim/MIPS/pipeline_mips处理器实现/control.v
  F:/codes/modelsim/MIPS/pipeline_mips处理器实现/processor.v
  F:/codes/modelsim/MIPS/pipeline_mips处理器实现/top.v
}
read_xdc F:/codes/modelsim/MIPS/pipeline_mips处理器实现/top.xdc
set_property used_in_implementation false [get_files F:/codes/modelsim/MIPS/pipeline_mips处理器实现/top.xdc]

synth_design -top top -part xc7a35tcpg236-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
